CPU = efm32
CPU_FAM = efm32pg12b
CPU_MODEL = efm32pg12b500f1024gm48

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_rtc
FEATURES_PROVIDED += periph_rtt
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart periph_uart_modecfg

# Put other features for this board (in alphabetical order)
FEATURES_PROVIDED += efm32_coretemp
FEATURES_PROVIDED += riotboot
